### ISSUE TITLE
[DEV] New Code for reading :)

### ISSUE THREAD

**Issue by cyberpunkbln** [Schoperation/SchopCraft#2]
Hello,

when you have time you can review my new code on my forked-repo. Hopefully some code are usefull for you. Everybody has his own design-pattern-using and oop-style and hope my new HazmatLigh Suit complain with your code-style.

Now i can go to the Nether and make the lava-pump ready with the hazmatlightsuit :).

In the near Future i will fork your new version and adapt my new code on this.

At the moment i have the problem that i only can use my Items when thermalfoundation and industrialforegoing. I have problems with the new json-recipe-system and i don't find source examples that uses IIngredientFactory. I Fail constantly with the new json-recipe-system.

At the moment i can only work with an ModConfig and this are useless.

Do you have Experience with the new Json Recipes factories and conditions or better with IIngredientFactory?

Greetz

**Comment by Schoperation** [comment]
In case you haven't found the answer, I have no clue about the JSON recipe factories with ingredients and stuff. JSON recipes just came out so unfortunately there aren't many that can help. Sorry.

As for your hazmat suit, it looks cool. It is definitely a pain to be in the nether with constant heat. Eventually I'll add something similar to your suit to deal with extreme heat, once I get around to seasons (where extreme heat would be a problem everywhere during the summer). I haven't been too sure on how to implement armor and your code definitely helps out with that.
