### ISSUE TITLE
[Suggestion] Remove Effects in Creative Mode

### ISSUE THREAD

**Issue by MasterEnderman** [Schoperation/SchopCraft#7]
Could you please remove the effects when the player is in creative mode? I don't like to get nausea all the time, when I'm testing stuff in a test world.

**Comment by Schoperation** [comment]
I was actually just thinking about this. Not exactly this, but thinking of making creative mode "freeze" the bars and stuff. This shouldn't be hard at all to implement, so I can do it pretty soon.

Thanks for pitching in!

**Comment by Schoperation** [comment]
Done
