### ISSUE TITLE
[Suggestion] More Config Options

### ISSUE THREAD

**Issue by MasterEnderman** [Schoperation/SchopCraft#8]
Would like some additional config options:

General
- change the rate how fast your body heats up
- change the rate how fast yout body cools down
- change how fast you become thirsty
- change how fast you become insane
- change how fast you dry

Item
- how much sips you can have out of a canteen
- how much sips you can have out of a waterbag

**Comment by Queglar** [comment]
Being able to set the impact items/blocks have on temperature/hydration/sanity would be pretty cool too.

From memory I think you could set blocks to be a heat source in Enviromine, but the ability to set any block as a heat source would make this super customisable for modded servers. If you could do the same with setting particular blocks to be cold sources alternatively that would be going a step above that. 

Setting a hydration and/or sanity for items is really just for all those extra food and drink items you invariably end up with.

**Comment by Schoperation** [comment]
I'll see what I can do

**Comment by CrankySupertoonArchive** [comment]
Might reopen but that Whitelist feature for heat levels will be really useful in my pack Rebirth 3
