### ISSUE TITLE
Russian and Ukrainian translations

### ISSUE THREAD

**Issue by TehenoPengin** [Schoperation/SchopCraft#9]
I made russian translation for SchopCraft.

[ru_RU.zip](https://github.com/Schoperation/SchopCraft/files/1584064/ru_RU.zip)

I hope this can be added to the mod :)
  
Edit: I found a little derp with my translation, here's the fixed version
[New ru_RU.zip](https://github.com/Schoperation/SchopCraft/files/1600280/ru_RU.zip)

**Comment by Schoperation** [comment]
This will be added. Thank you very much!

**Comment by TehenoPengin** [comment]
Also made Ukrainian translation :)
[uk_UA.zip](https://github.com/Schoperation/SchopCraft/files/1600290/uk_UA.zip)

**Comment by Schoperation** [comment]
Thanks! Just added.
